// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCO42RhnXlaA4GtQ9Rt_60bpjfrSlDlISY',
    appId: '1:474282387266:web:19284432a09b6dc7e9cadb',
    messagingSenderId: '474282387266',
    projectId: 'fluttertest1-31a1d',
    authDomain: 'fluttertest1-31a1d.firebaseapp.com',
    storageBucket: 'fluttertest1-31a1d.appspot.com',
    measurementId: 'G-GF1Z10BY3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUilHVIU_0tOBSHcy7X9eIMQGxsPMG1Sg',
    appId: '1:474282387266:android:24d13de0381898d0e9cadb',
    messagingSenderId: '474282387266',
    projectId: 'fluttertest1-31a1d',
    storageBucket: 'fluttertest1-31a1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEzqkQ96TJQSDn6IzpvUP2FN64HUj4_sk',
    appId: '1:474282387266:ios:d7c417059de2a18fe9cadb',
    messagingSenderId: '474282387266',
    projectId: 'fluttertest1-31a1d',
    storageBucket: 'fluttertest1-31a1d.appspot.com',
    iosBundleId: 'com.example.fluttertest1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEzqkQ96TJQSDn6IzpvUP2FN64HUj4_sk',
    appId: '1:474282387266:ios:a3e476147d5163c7e9cadb',
    messagingSenderId: '474282387266',
    projectId: 'fluttertest1-31a1d',
    storageBucket: 'fluttertest1-31a1d.appspot.com',
    iosBundleId: 'com.example.fluttertest1.RunnerTests',
  );
}
